<!-- ##### Breadcrumb Area Start ##### -->
    <section class="breadcrumb-area bg-img bg-overlay" style="background-image: url(img/single-bg.jpg);">
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <!-- Breadcrumb Text -->
                <div class="col-12">
                    <div class="breadcrumb-text">
                        <h2>Terms & Conditions</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Breadcrumb Area End ##### -->

    <!-- ##### Post Details Area Start ##### -->
    <section class="post-news-area section-padding-0-100">
        <div class="container">
            <div class="row justify-content-center">
                <!-- Post Details Content Area -->
                <div class="col-12">
                    <div class="mt-100">
                        <div class="post-details-content mb-100">
                            <h4>General</h4>
                        <p>This document outlines the Terms and Conditions governing the use of the products and/or services of Value Added Services for mobile and Internet (hereafter referred to as the Services). This service and website is fully operated and controlled by Techijam, TELEPLAY CC, Unit F7, Century Square, Heron Crescent, Century City 7441. </p>
                        <p>User Agreement</p>
                        <p>These Terms and Conditions are an agreement between you and Techijam with respect to the subscription services made available by Techijam. We reserve the right to modify, change or otherwise alter these terms and conditions at our sole discretion, at any time. Please review the terms and conditions periodically. Such changes and/or modifications shall become effective immediately upon the posting thereof. Without limiting the foregoing, we may occasionally notify you via SMS about changes to the service or provide notices of changes by displaying notices or links to notices to you generally on the service.</p>
                        <p>As noted in the Terms and Conditions, you must be 18 years of age or older in order to use the Services. If you are under age 18, you may not use the Services under any circumstances or for any reason. By opening an account, downloading the Application, and/or otherwise using the Services, you represent that you are at least 18 years old. By accepting these Terms & Conditions, you agree to receive marketing offers which will be sent over SMS. This service must not be used to intentionally engage in illegal conduct. We will not knowingly create, store or disseminate any illegal content, infringe copyright or infringe any intellectual property rights. Service must not be used to send spam or promote sending of spam. </p>
                        <p>By subscribing to these Services, you will get access to a high-quality mobile content portal with content ranging from security tips, movie trailers, gossips, ringtones, wallpapers, video, jokes, horoscopes, fun games and more information via subscriptions, both via the mobile phone and from the internet. </p>
                        <p>UThis service offers you a free trial period which will be available to you without charge until it’s expiration after 60 days. You may cancel your free trial subscription prior to the end of the free trial period. If you do not cancel your free trial subscription by that time, you will be charged by our normal subscription rate. Subscription can be cancelled by sending STOP to 41580. You may only use this trial offer once. We may terminate or modify this trial program at any time and in our sole discretion. </p>
                        <p> TClients are paying a fixed daily fee (R7/day) as their subscription fee for getting their login credentials with which they have the approach to content in techijam.site. Subscribers have the right to unsubscribe from the service at any time. Standard SMS rates apply. Billings errors are charged. Network fees may apply. Service is available via WEB and WAP. By subscribing to this service, you may be sent occasional marketing promotions by our partner Cellubet. </p>
                        <p> To cancel the Service, you can send a text message containing the word STOP and send it through to 41580. You will be unsubscribed with immediate effect. If you have any queries about our service please contact our Support at <a href="mailto:info@techijam.site"</a>. Support line: 0105970857. This service must be only used with the bill payers permission. </p>
                        <p>Method of payment </p>
                        <p>  The amounts of the Services provided by the Provider are billed and invoiced via the mobile operator with which the User has concluded the corresponding telephone service. This invoice indicates the identity of the third company with which the provider entered into the payment management service. For users who use a mobile phone with the prepaid card, the amount of products and services provided by the provider is deducted from the current balance of the user.
                        The service is provided on an 'as is' basis without warranties of any kind, either expressed or implied, including but not limited to warranties of title or implied warranties, other than those warranties which are imposed by and incapable of exclusion, restriction or modification under the laws applicable to this agreement. Neither TELEPLAY CC nor its affiliates endorse or are responsible for the accuracy or reliability of any opinion, advice or statement on the Service.
                        </p>
                        <p> TELEPLAY CC is a member of WASPA and is bound by the WASPA Code of Conduct. Customers have the right to approach WASPA to lodge a complaint in accordance with the WASPA complaints procedure. TELEPLAY CC may be required to share information relating to a service or a customer with WASPA for the purpose of resolving a complaint. WASPA web site: www.waspa.org.za". </p>
                        <p> We reserve the right, at our sole discretion, to change, modify or otherwise alter these terms and conditions at any time. Such changes and/or modifications shall become effective immediately upon the posting thereof. Without limiting the foregoing, we may occasionally notify you via SMS about changes to the service or provide notices of changes by displaying notices or links to notices to you generally on the service. Please review the terms and conditions periodically. Your continued use of the service following the posting of changes and/or modifications will constitute your acceptance of the revised terms and conditions. </p>
                        <p>BY ACCESSING THE SERVICE, YOU ACCEPT, WITHOUT LIMITATION OR QUALIFICATION, ALL OF THE TERMS AND CONDITIONS IN THIS USER AGREEMENT.</p>
                        <p> Internet</p>
                        <p>Neither TELEPLAY CC nor any of its subsidiaries, division, affiliates, agents, representatives or licensors shall be liable to you or anyone else for any loss or injury or any direct, indirect, incidental, consequential, punitive or similar damages arising out of your access or use of, or your inability to access or use, the service and the information available on the service or arising out of any action taken in the response to or as a result of any information available on the service. You hereby waive any and all claims against TELEPLAY CC and its subsidiaries, divisions, affiliates, agents, representatives, and licensors arising out of your use of the service and the information available and the information available thereon.  </p>
                        <p>You accept all responsibility for, and hereby indemnify and hold us harmless from and against, any actions taken by any user authorized to use your account, including, but not limited to, the disclosure of login credentials to third parties. Techijam does not monitor or store the content of private messages that users send from the service and cannot in any way be held responsible for the content of user messages sent over the techijam.site web or wap page.</p>
                        <p>If for any reason this Service is not capable of running as planned due to an infection by a computer virus, bugs, tampering, unauthorized intervention, fraud, technical failures, or any other causes beyond the control of the Service Providers which corrupt or affect the administration, security, fairness, integrity, or proper conduct of this Service, the Service Providers reserve the right at its sole discretion, to disqualify any individual who tampers with the entry process, and to cancel, terminate, modify or suspend the Service. The Service Provider is not responsible for any problems or technical malfunctions of any telephone network or telephone lines, computer on-line systems, servers, or providers, computer equipment, software, failure of any email or entry to be received by the Service Provider due to technical problems, human error or traffic congestion on the Internet or at any Web site, or any combination thereof, including any injury or damage to participant's or any other person's computer relating to or resulting from participating in this Service or downloading any materials in this Service.</p>
                        <p> SPONSORS ARE NOT RESPONSIBLE FOR INCOMPATIBILITY OF ENTRANT'S HARDWARE, SOFTWARE OR BROWSER TECHNOLOGY WITH SPONSOR'S HARDWARE, SOFTWARE OR BROWSER TECHNOLOGY. NOTE: ANY ATTEMPT TO DELIBERATELY DAMAGE ANY WEB SITE OR UNDERMINE THE LEGITIMATE OPERATION OF THE SERVICE IS A VIOLATION OF CRIMINAL AND CIVIL LAWS. SHOULD SUCH AN ATTEMPT BE MADE, SPONSOR RESERVES THE RIGHT TO SEEK DAMAGES OR OTHER REMEDIES FROM ANY SUCH PERSON/S RESPONSIBLE FOR THE ATTEMPT TO THE FULLEST EXTENT PERMITTED BY LAW.</p>
                        <p>Violation of the Terms</p>
                        <p>You understand and agree that in our sole discretion, and without prior notice, we may terminate your access to the service and/or deactivate or delete your membership account if we determine that you have violated our Terms and Conditions. The materials used and displayed on the Service, including, but not limited to, text, photographs, graphics, illustrations and artwork, music, video and sound, and names, logos and trademarks, are the property of TELEPLAY CC or its affiliates or licensors are protected by copyright, trademark and other laws. Any such content may be displayed solely for your personal, non-commercial use.</p>
                        <p>
                        The Company grants you a limited, non-exclusive, non-transferable, revocable right to download the Downloads to your compatible device solely for your own non-commercial use. You understand and agree that you may not download, reproduce, modify, display, perform, transfer, distribute or otherwise use the Downloads except as expressly provided in this Agreement. You understand and agree that you may not authorize, encourage or allow any Downloads used or obtained by you to be reproduced, modified, displayed, performed, transferred, distributed or otherwise used by any other party, and you agree that you will take all reasonable steps to prevent any unauthorized reproduction and/or other use of them. We have the right to take down any content that We as a member consider illegal or for which we have received a take-down notice.
                         </p>
                                                
                        
                        <p> If in Service Providers' sole opinions, there is any suspected or actual evidence of electronic or non-electronic tampering with any portion of the Service, or if technical difficulties compromise the integrity of the Service, Service Providers reserve the right to terminate the Service, disqualify any individual who has tampered with Service. Any attempt to deliberately hamper the operation of this Service is unlawful and subject to legal action by Service providers and/or their agents. By using this Service, entrants: (1) agree to be bound by these rules; (2) agree to release Service providers, and their respective parent companies, and their employees, subsidiaries, affiliates, divisions, advertising and promotion, fulfillment and/or judging agencies, and related entities from any and all liability for any loss, harm, damages, costs or expenses, including without limitation property damages, personal injury and/or death arising out of participating in this Service, or the acceptance, possession, use or misuse of any Product, and claims based on publicity rights, defamation or invasion of privacy and merchandise delivery; and (3) consent to the use of their names, voices, pictures, and likenesses for advertising and promotional purposes in any medium throughout the world in perpetuity without additional compensation unless prohibited by law. Service provider may discontinue the Service at any time. Service providers may terminate any Service or decide to modify it in any manner that it deems fair and equitable to participants if it becomes aware of any occurrence that would materially affect the Service's security and fairness. Service providers may prohibit individuals from participating in Service and disqualify entries if they (1) attempt to enter the Service through any means other than as described in these Rules, (2) attempt to disrupt the Service or circumvent the terms and conditions of these Rules in any way or (3) repeatedly show a disregard for the Service Rules or act (a) in an inappropriate manner, or (b) with an intent to annoy, abuse, threaten or harass any other entrant or Service providers. Service Providers' decisions with respect to the Service are final. TELEPLAY CC has the right to suspend or terminate the services of any customer who does not comply with these terms and conditions or any other related contractual obligations. </p>
                        <p> Neither Nexus Enterprises LTD nor any of its subsidiaries, division, affiliates, agents, representatives or licensors shall be liable to you or anyone else for any loss or injury or any direct, indirect, incidental, consequential, punitive or similar damages arising out of you access or use of, or you inability to access or use, the service and the information available on the service or arising out of any action taken in the response to or as a result of any information available on the service. You hereby waive any and all claims against Nexus Enterprises LTD, Cellubet (PTY) LTD or any of the aforementioned companies and their subsidiaries, divisions, affiliates, agents, representatives and licensors arising out of your use of the service and the information available and the information available thereon. </p>
                        <p> ou accept all responsibility for, and hereby indemnify and hold us harmless from and against, any actions taken by any user authorized to use your account, including, but not limited to, disclosure of login credentials to third parties. By using the Service, you release us, our subsidiaries, and affiliates from any and all liabilities regarding your participation in the Service. Funstore.club does not monitor or store the content of private messages that users send from the service and cannot in any way be held responsible for the content of user messages sent over the funstore.club WEB or WAP page.  </p>
                        
                
                    </div>
                        </div>
                    </div>
                </div>
        </div>
    </section>
    <!-- ##### Post Details Area End ##### -->
